version: '3.7'

services:
  back-app:
    build:
      context: .
    restart: always
    environment:
      FLASK_APP: app
      API_TOKEN: ${API_TOKEN}
      DATABASE_URI: postgresql+psycopg2://postgres:root@mariadb:3306/snazzyevents
    ports:
      - 5000:5000

  mariadb:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myfingerprint
