# This is a basic workflow to help you get started with Actions

name: Build/Push and deploy the application

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependenties
      shell: bash
      run: |
        wget https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_openbsd_amd64.zip
        unzip terraform_0.13.4_openbsd_amd64.zip
        terraform -v
        sudo apt update -y
        sudo apt install -y kubectl git
        
    # Runs a single command using the runners shell
    - name: Build Docker image
      shell: bash
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        docker-compose build

    # Runs a single command using the runners shell
    - name: Push Docker image
      # master branch only
      if: github.ref == 'refs/heads/master'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo ${GH_TOKEN} | docker login docker.pkg.github.com -u paretl --password-stdin
        docker tag backapp_back-app:latest docker.pkg.github.com/mycarbonfootprint/backapp/backapp:${GITHUB_SHA}
        docker push docker.pkg.github.com/mycarbonfootprint/backapp/backapp:${GITHUB_SHA}
        docker tag backapp_back-app:latest docker.pkg.github.com/mycarbonfootprint/backapp/backapp:latest
        docker push docker.pkg.github.com/mycarbonfootprint/backapp/backapp:latest

    # Runs a single command using the runners shell
    - name: Prepare GCP service account file
      # master branch only
      if: github.ref == 'refs/heads/master'
      shell: bash
      env:
        GCP_SERVICE_ACCOUNT_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_FILE }}
      run: |
        echo "${GCP_SERVICE_ACCOUNT_FILE}" > deployment/service-account.json

    # Runs a single command using the runners shell
    - name: Deploy it on Kube cluster
      # master branch only
      if: github.ref == 'refs/heads/master'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      run: |
        export SCW_ACCESS_KEY=SCW6VHPETC96DKKNPCNZ
        export SCW_SECRET_KEY=${SCW_SECRET_KEY}
        export SCW_DEFAULT_REGION=fr-par
        export SCW_DEFAULT_ZONE=fr-par-1
        export SCW_DEFAULT_ORGANIZATION_ID=${SCW_DEFAULT_ORGANIZATION_ID}
        export GOOGLE_BACKEND_CREDENTIALS=../service-account.json
        export TF_VAR_registry_password=${GH_TOKEN}
        export VERSION_TO_DEPLOY=${GITHUB_SHA}
        ./deployment/deployment.sh
